### ISSUE TITLE
Missing json dependency

### ISSUE THREAD

**Issue by jonasfagundes** [rlister/awful#9]
The awful fails without `json` dependency in the `Gemfile`.

Steps to reproduce:
1. Gemfile:

```
source 'https://rubygems.org'
gem 'awful', '0.0.130'
```
1. Dockerfile:

```
FROM alpine:3.4

RUN apk update && \
    apk upgrade && \
    apk add bash build-base ca-certificates ruby ruby-dev ruby-io-console ruby-bundler && \
    rm -rf /var/cache/apk/*

RUN gem install bundler --no-rdoc --no-ri

WORKDIR /app
ADD Gemfile* /app/
RUN bundle install
```
1. `$ docker build -t test .`
2. `$ docker run -it test bash`
   5.

```
bash-4.3# cf
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/gems/2.3.0/gems/jmespath-1.3.0/lib/jmespath.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-2.3.22/lib/aws-sdk.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/gems/2.3.0/gems/awful-0.0.130/lib/awful.rb:4:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/gems/2.3.0/gems/awful-0.0.130/bin/cf:4:in `<top (required)>'
    from /usr/bin/cf:23:in `load'
    from /usr/bin/cf:23:in `<main>'
bash-4.3#
```

If we add `gem json` to `Gemfile` before the docker build `cf` shows an usage message.

**Comment by rlister** [comment]
Fixed by https://github.com/rlister/awful/commit/df8c25bfad011dfa4aeea282832190bcd596f936
